# Generated by Django 5.1.2 on 2024-10-27 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tweet", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweet",
            old_name="tweet",
            new_name="text",
        ),
    ]
